const PROFILE_ACTION_TYPE_GET = "PROFILE_ACTION_TYPE_GET";
const PROFILE_ACTION_TYPE_GET_IS_REQUESTING = "PROFILE_ACTION_TYPE_GET_IS_REQUESTING"
const PROFILE_ACTION_TYPE_GET_SUCCESS = "PROFILE_ACTION_TYPE_GET_SUCCESS";
const PROFILE_ACTION_TYPE_GET_FAIL = "PROFILE_ACTION_TYPE_GET_FAIL";
export {
    PROFILE_ACTION_TYPE_GET,
    PROFILE_ACTION_TYPE_GET_IS_REQUESTING,
    PROFILE_ACTION_TYPE_GET_SUCCESS,
    PROFILE_ACTION_TYPE_GET_FAIL
}