const PROFILE_ACTION_TYPE_GET = "PROFILE_ACTION_TYPE_GET";
const PROFILE_ACTION_TYPE_GET_IS_REQUESTING = "PROFILE_ACTION_TYPE_GET_IS_REQUESTING"
const PROFILE_ACTION_TYPE_GET_SUCCESS = "PROFILE_ACTION_TYPE_GET_SUCCESS";
export {
    PROFILE_ACTION_TYPE_GET,
    PROFILE_ACTION_TYPE_GET_IS_REQUESTING,
    PROFILE_ACTION_TYPE_GET_SUCCESS
}